import namespace from 'helpers/namespace';

export default namespace({
  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,
  START_GET_PROFILE: null,
  FINISH_GET_PROFILE: null,

  CREATE_PROFILE_REQUEST: null,
  CREATE_PROFILE_SUCCESS: null,
  CREATE_PROFILE_FAILURE: null,
  START_CREATE_PROFILE: null,
  FINISH_CREATE_PROFILE: null,

  CREATE_SESSION_REQUEST: null,
  CREATE_SESSION_SUCCESS: null,
  CREATE_SESSION_FAILURE: null,
  START_CREATE_SESSION: null,
  FINISH_CREATE_SESSION: null,

  CREATE_ADMIN_SESSION_REQUEST: null,
  CREATE_ADMIN_SESSION_SUCCESS: null,
  CREATE_ADMIN_SESSION_FAILURE: null,
  START_CREATE_ADMIN_SESSION: null,
  FINISH_CREATE_ADMIN_SESSION: null,

  ADD_ADMIN_REQUEST: null,
  ADD_ADMIN_SUCCESS: null,
  ADD_ADMIN_FAILURE: null,

  CLEAR_USER_DATA: null,

}, 'USER');
